name: Enforcing pylint checks
on:
  push:
    branches:
      - master
      - develop
      - testing
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  update_python:
    runs-on: ubuntu-latest
    name: Running pylint checks
    steps:
      - name: install software-properties-common
        run: sudo apt-get install software-properties-common
      - name: add deadsnakes repository
        run: sudo add-apt-repository -y ppa:deadsnakes/ppa
      - name: add gdal repository
        run: sudo add-apt-repository ppa:ubuntugis/ppa
      - name: update apt-get
        run: sudo apt-get update
      - name: install gdal-deps
        run: sudo apt-get install -y gdal-bin libgdal-dev gcc g++


      - name: test python version
        run: python3 --version
      - name: install python3.7
        run: sudo apt-get install -y --no-install-recommends python3.7-dev python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
      - name: test python version2
        run: python3 --version

      - name: find gdal version
        run: ogrinfo --version
      - name: Update pip
        run: python3 -m pip install --upgrade --no-cache-dir pip
        id: pip-install
      - name: Fetch/update setuptools
        run: python3 -m pip install --upgrade --no-cache-dir setuptools
        id: setuptools-install
      - name: install gdal
        run: python3 -m pip install GDAL==2.4.2.*


#      - name: Install Python 3.7
#        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
#        id: install_python_3_7
#      - name: get gdal dependencies
#        run: 'sudo apt-get install -y python3-gdal gdal-bin libgdal-dev gcc g++ python3.7-dev'


#
#      - name: numpy install
#        run: python3 -m pip install --upgrade --no-cache-dir numpy
#      - name: gdal install
#        run: python3 -m pip install --no-cache-dir pygdal==2.2.3.*
#
#
      - name: Fetch/update pylint
        run: python3 -m pip install --upgrade --no-cache-dir pylint
        id: pylint-install
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Finding files
        run: find . -type f -name "*.py" > action_pylint_files.txt
        id: find-python-files
      - name: Install system requirements from source
        shell: bash
        run: 'sudo [ -s "packages.txt" ] && (cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
        id: install-system-reqs
      - name: Install Python requirements from source
        shell: bash
        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
        id: install-python-reqs
      - name: Run action pylint script
        shell: bash
        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
        id: run-special-action-script
      - name: Fetching pylint.rc file
        run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
        id: fetch_pylint_resource
      - name: Listing
        run: ls -la
      - name: Files to lint
        run: cat action_pylint_files.txt
      - name: Running pylint
        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc