name: Enforcing pylint checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  update_python:
    runs-on: ubuntu-latest
    name: Running pylint checks
    steps:
      - name: Install Python 3.7
        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
        id: install_python_3_7
      - name: Update pip
        run: python3 -m pip install --upgrade --no-cache-dir pip
        id: pip-install
      - name: Fetch/update setuptools
        run: python3 -m pip install --upgrade --no-cache-dir setuptools
        id: setuptools-install
      - name: Fetch/update pylint
        run: python3 -m pip install --upgrade --no-cache-dir pylint
        id: pylint-install
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Install system requirements from source
        shell: bash
        run: '[ -s "packages.txt" ] && (cat /home/extractor/packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
        id: install-system-reqs
      - name: Install Python requirements from source
        shell: bash
        run: '[ -s /home/extractor/requirements.txt ] && (python3 -m pip install --no-cache-dir -r /home/extractor/requirements.txt) || (echo "No Python packages to install")'
        id: install-python-reqs
      - name: Fetching pylint.rc file
        run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
        id: fetch_pylint_resource
      - name: Listing
        run: ls -la
      - name: Finding files
        run: find . -type f -name "*.py" | xargs echo
      - name: Running pylint
        run: find . -type f -name "*.py" | xargs python3 -m pylint --rcfile ./pylint.rc
